# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Blake Downward
description: "Welcome! I’m Blake - a developer from Adelaide who designs tools and systems that run themselves. Most of my projects live at the edge of data, automation, and design - building things that help small teams work smarter, faster, and with less noise. I like simple builds, clean code, and tools that quietly get the job done. Feel free to check out my work below or get in touch with me via GitHub or LinkedIn."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Simple. Clean. <span style="color:#f58506"> Systems </span>
location: "Adelaide, Australia"
resume_url: /docs/Blake_Downward_CV_web_0225.pdf
avatar_image: /img/Blake-Profile-Img.png

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/blake-downward" # Add your linkedln handle
github: "https://github.com/blakedownward"  # Add your github handle

paginate: 10
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: nesteded # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/




